<?php
debug($foo);
GeneralUtility::debug();
print_r();
var_dump();
xdebug();
// debug($foo);
// GeneralUtility::debug();
// print_r();
// var_dump();
// xdebug();
/* debug($foo); */
/* GeneralUtility::debug(); */
/* print_r(); */
/* var_dump(); */
/* xdebug(); */
# debug($foo);
# GeneralUtility::debug();
# print_r();
# var_dump();
# xdebug();
if ($this->debug) {
	$pt = GeneralUtility::milliseconds();
}

class debug {
	public function debug($var = '', $header = '', $group = 'Debug') {
		$foo = 'bar';
	}
}

DebugUtility::debug();

final class DebugUtility {
	public static function debug($var = '', $header = '', $group = 'Debug') {

	}
}