<?php
function InvalidName($param) {
	$var;
}
function invalid_name($param) {
	$var;
}
function invalid_Name($param) {
	$var;
}
function Invalid_name($param) {
	$var;
}
function Invalid_Name($param) {
	$var;
}
function invaliDName($param) {
	$var;
}

function __autoload() {
	$var;
}

class foo {

	function InvalidName($param) {
		$var;
	}

	function invalid_name($param) {
		$var;
	}

	function invalid_Name($param) {
		$var;
	}

	function Invalid_name($param) {
		$var;
	}

	function Invalid_Name($param) {
		$var;
	}

	function invaliDName($param) {
		$var;
	}

	public function __construct() {
		$var;
	}

	public function __destruct() {
		$var;
	}

	public function __call() {
		$var;
	}

	public function __callStatic() {
		$var;
	}

	public function __get() {
		$var;
	}

	public function __set() {
		$var;
	}

	public function __isset() {
		$var;
	}

	public function __unset() {
		$var;
	}

	public function __sleep() {
		$var;
	}

	public function __wakeup() {
		$var;
	}

	public function __toString() {
		$var;
	}

	public function __invoke() {
		$var;
	}

	public function __set_state() {
		$var;
	}

	public function __clone() {
		$var;
	}
}
?>