<?php
function InvalidName($param) {
	$var;
}
function invalid_name($param) {
	$var;
}
function invalid_Name($param) {
	$var;
}
function Invalid_name($param) {
	$var;
}
function Invalid_Name($param) {
	$var;
}
function invaliDName($param) {
	$var;
}

function __autoload() {
	$var;
}

class foo {

	function InvalidName($param) {
		$var;
	}

	function invalid_name($param) {
		$var;
	}

	function invalid_Name($param) {
		$var;
	}

	function Invalid_name($param) {
		$var;
	}

	function Invalid_Name($param) {
		$var;
	}

	function invaliDName($param) {
		$var;
	}

	public function __construct() {
		$var;
	}

	public function __destruct() {
		$var;
	}

	public function __call() {
		$var;
	}

	public function __callStatic() {
		$var;
	}

	public function __get() {
		$var;
	}

	public function __set() {
		$var;
	}

	public function __isset() {
		$var;
	}

	public function __unset() {
		$var;
	}

	public function __sleep() {
		$var;
	}

	public function __wakeup() {
		$var;
	}

	public function __toString() {
		$var;
	}

	public function __invoke() {
		$var;
	}

	public function __set_state() {
		$var;
	}

	public function __clone() {
		$var;
	}

	/**
	 * Finds out the answer to life, the universe and everything.
	 *
	 * @return void
	 */
	public function get42() {
	}

	/**
	 * Converts the universe to UTF-8.
	 *
	 * @return void
	 */
	public function convertToUtf8String() {
	}

	function pi_autoCache() {}

	function pi_classParam() {}

	function pi_fooBarBaz() {}
}

function pi_autoCache() {}

function pi_classParam() {}

function pi_exec_query() {}

function pi_getCategoryTableContents() {}

function pi_getClassName() {}

function pi_getEditIcon() {}

function pi_getEditPanel() {}

function pi_getFFvalue() {}

function pi_getFFvalueFromSheetArray() {}

function pi_getLL() {}

function pi_getPageLink() {}

function pi_getPidList() {}

function pi_getRecord() {}

function pi_initPIflexForm() {}

function pi_isOnlyFields() {}

function pi_linkToPage() {}

function pi_linkTP() {}

function pi_linkTP_keepPIvars() {}

function pi_linkTP_keepPIvars_url() {}

function pi_list_browseresults() {}

function pi_list_header() {}

function pi_list_linkSingle() {}

function pi_list_makelist() {}

function pi_list_modeSelector() {}

function pi_list_query() {}

function pi_list_row() {}

function pi_list_searchBox() {}

function pi_loadLL() {}

function pi_openAtagHrefInJSwindow() {}

function pi_prependFieldsWithTable() {}

function pi_RTEcssText() {}

function pi_setClassStyle() {}

function pi_setPiVarDefaults() {}

function pi_wrapInBaseClass() {}

function pi_fooBar() {}

function user_MediaType(array &$config, t3lib_TCEforms $parentObject) {}

?>