<?php
/**
 * This is a doc block comment
 * All comments shouldn´t longer than 80 character
 * But this line is longer than 80 characters cause I write more characters than eighteen.
 */

					// This is a valid comment line cause its shorter than 80 characters.
					// The comment begin with the chars "//" and not in the beginning of the line !!!

// This is a single line comment with a really long text and this message should raise an error, when it don`t we got a bug and this would be bad.

/*
 * This file is part of the TYPO3 CMS project.
 *
 * It is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, either version 2
 * of the License, or any later version.
 *
 * For the full copyright and license information, please read the
 * LICENSE.txt file that was distributed with this source code.
 *
 * The TYPO3 project - inspiring people to share!
 */

/**
 * Implements a Categorytree for the Link-Commerce Module
 * A tree can have n leafs, and leafs can in itself contain other leafs
 *
 * Class Tx_Commerce_ViewHelpers_Browselinks_CategoryTree
 *
 * @author 2008-2011 Firstname Lastname <email@example.de>
 */
class Tx_Commerce_ViewHelpers_Browselinks_CategoryTree extends Tx_Commerce_Tree_Browsetree {

}