<?php
/**
 * This is a doc block comment
 * All comments shouldn´t longer than 80 character
 * But this line is longer than 80 characters cause I write more characters than eighteen.
 */

					// This is a valid comment line cause its shorter than 80 characters.
					// The comment begin with the chars "//" and not in the beginning of the line !!!

// This is a single line comment with a really long text and this message should raise an error, when it don`t we got a bug and this would be bad.