<?php 

/****** False ******/
// The answer of life, the universe and everything
$foo = 42;

/****** Correct ******/
	// The answer of life, the universe and everything
$foo = 42;

if ($foo == $bar) {
	$var = 3;

	switch ($var) {
		case 1:
			// something()
			something();
			break;
		case 2:
				// somethingelse()
				// multiple line comment
			somethingelse();
			break;
		case 3:
					// moresomethingelse()
			moresomethingelse();
			break;
		default:
		// default tree
			break;
	}
}
?>