<?php

switch($foo) {
	case 1:
		doSomething();
	break;
	case 2:
		doSomethingElse();
		break;
	default:
}



if ($foo) {
	$var = $int;
		// huselpusel
	break;
}

while ($i < $j) {
	if ($foo == $bar) {
		doSomething();
		break;
	} else {
		if ($oof == $rab) {
		break;
		}
	}
	break;
}



switch($foo) {
	case 1:
		doSomething();
		break;
	default:
	break;
}

do {
	doSomething();
	
	if ($i == $j) {
		doSomethingElse();
			break;
	}
	break;
} while ($foo != $bar);

for ($i=10; $i>0; $i--) {
	doSomething();

	break;
}

?>